apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
spec:
  selector:
    matchLabels:
      app: yolo
  replicas: 1
  template:
    metadata:
      labels:
        app: yolo
    spec:
      hostNetwork: true
      containers:
        - name: yolo
          image: vineet22h/yolov4_desktopapp
          env:
            - name: "DISPLAY"
              value: $DISPLAY
          volumeMounts:
            - name: "dev-video0"
              mountPath: /dev/video0  
      volumes:
      - name: "dev-video0"
        hostPath:
          path: /dev/video0